name: Build latest
on: [push]

concurrency:
  group: ${{ github.ref }}-latest
  cancel-in-progress: true

jobs:
  build-mono:
    if: github.ref_name == github.event.repository.default_branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Compile MCNebula using mono
        shell: bash
        id: compile
        run: |
          msbuild MCNebula.sln /p:Configuration=Release
          cp -R bin/Release bin/Release_normal
          rm bin/Release/MCNebula_.dll bin/Release/MCNebula_.pdb
          msbuild MCNebula/MCNebula_.csproj /p:Configuration=Release /t:Rebuild /p:DefineConstants="DEV"

      - uses: ./.github/actions/notify_failure
        if: ${{ always() && steps.compile.outcome == 'failure' }}
        with:
          NOTIFY_MESSAGE: 'Failed to compile MCNebula .NET build! <@999409543001931788>'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL }}'
          
      - uses: ./.github/actions/notify_success
        if: ${{ always() && steps.compile.outcome == 'success' }}
        with:
          SOURCE_FILE: 'bin/Release_normal'
          DEST_NAME: 'MCNebula'
          NOTIFY_MESSAGE: 'Successfully compiled MCNebula .NET build.'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL }}'
          
      - uses: ./.github/actions/notify_success
        if: ${{ always() && steps.compile.outcome == 'success' }}
        with:
          SOURCE_FILE: 'bin/Release'
          DEST_NAME: 'MCNebula-dev'
          NOTIFY_MESSAGE: 'Successfully compiled MCNebula .NET Dev build.'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL }}'
